
export const DOCS = [
  {
    id: 'leave-policy-2026',
    title: 'سياسة إجازات الموظفين 2026',
    cat: 'HR',
    dept: 'الموارد البشرية',
    by: 'أحمد المدير',
    date: '2026-06-28',
    desc: 'تحدّد هذه الوثيقة سياسة الإجازات السنوية والمرضية والطارئة للموظفين، بما يشمل آلية طلب الإجازة والموافقة عليها من المدير المباشر.',
    docDate: '2026-01-14',
    uploadedAt: '2026-01-15 · 10:32',
    updatedAt: '2026-02-02',
    files: [
      { id: 'f1', name: 'نموذج طلب إجازة.pdf', size: '240 KB', uploadedBy: 'أحمد المدير' },
      { id: 'f2', name: 'جدول الرصيد السنوي.xlsx', size: '88 KB', uploadedBy: 'أحمد المدير' },
      { id: 'f3', name: 'ملحق التعديلات - يناير.docx', size: '54 KB', uploadedBy: 'سارة الموظفة' },
    ],
  },
  {
    id: 'finance-report-q2',
    title: 'تقرير الأداء المالي - الربع الثاني',
    cat: 'Finance',
    dept: 'المالية',
    by: 'ليلى حسن',
    date: '2026-06-25',
    desc: 'تقرير مفصل عن الأداء المالي للمؤسسة خلال الربع الثاني من عام 2026.',
    docDate: '2026-06-20',
    uploadedAt: '2026-06-25 · 09:10',
    updatedAt: '2026-06-25',
    files: [{ id: 'f1', name: 'تقرير الربع الثاني.pdf', size: '512 KB', uploadedBy: 'ليلى حسن' }],
  },
  {
    id: 'office-supply-contract',
    title: 'عقد توريد معدات مكتبية',
    cat: 'Contracts',
    dept: 'الشؤون القانونية',
    by: 'عمر يوسف',
    date: '2026-06-20',
    desc: 'عقد توريد معدات وأثاث مكتبي للمقر الرئيسي للمؤسسة.',
    docDate: '2026-06-15',
    uploadedAt: '2026-06-20 · 14:20',
    updatedAt: '2026-06-20',
    files: [{ id: 'f1', name: 'العقد الموقّع.pdf', size: '310 KB', uploadedBy: 'عمر يوسف' }],
  },
  {
    id: 'archiving-project-report',
    title: 'تقرير سير مشروع الأرشفة',
    cat: 'Reports',
    dept: 'إدارة المشاريع',
    by: 'سارة الموظفة',
    date: '2026-06-18',
    desc: 'تقرير دوري يوثّق سير العمل في مشروع أرشفة الوثائق الرقمية.',
    docDate: '2026-06-16',
    uploadedAt: '2026-06-18 · 11:05',
    updatedAt: '2026-06-18',
    files: [{ id: 'f1', name: 'تقرير المشروع.docx', size: '120 KB', uploadedBy: 'سارة الموظفة' }],
  },
  {
    id: 'internal-hiring-guide',
    title: 'دليل التوظيف الداخلي',
    cat: 'HR',
    dept: 'الموارد البشرية',
    by: 'أحمد المدير',
    date: '2026-06-12',
    desc: 'دليل إجراءات التوظيف الداخلي وترقية الموظفين.',
    docDate: '2026-06-01',
    uploadedAt: '2026-06-12 · 08:40',
    updatedAt: '2026-06-12',
    files: [{ id: 'f1', name: 'دليل التوظيف.pdf', size: '180 KB', uploadedBy: 'أحمد المدير' }],
  },
  {
    id: 'hq-lease-contract',
    title: 'عقد إيجار المقر الرئيسي',
    cat: 'Contracts',
    dept: 'الشؤون القانونية',
    by: 'عمر يوسف',
    date: '2026-06-05',
    desc: 'عقد إيجار سنوي للمقر الرئيسي للمؤسسة.',
    docDate: '2026-05-28',
    uploadedAt: '2026-06-05 · 16:00',
    updatedAt: '2026-06-05',
    files: [{ id: 'f1', name: 'عقد الإيجار.pdf', size: '410 KB', uploadedBy: 'عمر يوسف' }],
  },
  {
    id: 'budget-2027',
    title: 'الموازنة التقديرية 2027',
    cat: 'Finance',
    dept: 'المالية',
    by: 'ليلى حسن',
    date: '2026-05-30',
    desc: 'الموازنة التقديرية للعام المالي 2027 لجميع الأقسام.',
    docDate: '2026-05-25',
    uploadedAt: '2026-05-30 · 13:15',
    updatedAt: '2026-05-30',
    files: [{ id: 'f1', name: 'الموازنة 2027.xlsx', size: '96 KB', uploadedBy: 'ليلى حسن' }],
  },
  {
    id: 'employee-satisfaction-report',
    title: 'تقرير رضا الموظفين',
    cat: 'Reports',
    dept: 'الموارد البشرية',
    by: 'سارة الموظفة',
    date: '2026-05-22',
    desc: 'نتائج استبيان رضا الموظفين السنوي وتوصيات التحسين.',
    docDate: '2026-05-18',
    uploadedAt: '2026-05-22 · 10:50',
    updatedAt: '2026-05-22',
    files: [{ id: 'f1', name: 'نتائج الاستبيان.pdf', size: '275 KB', uploadedBy: 'سارة الموظفة' }],
  },
];

export const USERS = [
  { id: 'u1', name: 'أحمد المدير', email: 'admin@nuskha.org', dept: 'الإدارة العامة', role: 'Admin', active: true },
  { id: 'u2', name: 'ليلى حسن', email: 'layla.hassan@nuskha.org', dept: 'المالية', role: 'Manager', active: true },
  { id: 'u3', name: 'عمر يوسف', email: 'omar.yousef@nuskha.org', dept: 'الشؤون القانونية', role: 'Manager', active: true },
  { id: 'u4', name: 'سارة الموظفة', email: 'sara.emp@nuskha.org', dept: 'إدارة المشاريع', role: 'Employee', active: true },
  { id: 'u5', name: 'خالد ناصر', email: 'khaled.n@nuskha.org', dept: 'الموارد البشرية', role: 'Employee', active: false },
];

export const DEPTS = [
  { id: 'd1', name: 'الموارد البشرية', desc: 'شؤون الموظفين والتوظيف والإجازات', users: 5, docs: 32 },
  { id: 'd2', name: 'المالية', desc: 'الميزانيات والتقارير المالية', users: 3, docs: 27 },
  { id: 'd3', name: 'الشؤون القانونية', desc: 'العقود والوثائق القانونية', users: 2, docs: 19 },
  { id: 'd4', name: 'إدارة المشاريع', desc: 'متابعة المشاريع الداخلية', users: 6, docs: 24 },
];

export const CATS = [
  { id: 'c1', name: 'HR', desc: 'وثائق الموارد البشرية', docs: 38 },
  { id: 'c2', name: 'Finance', desc: 'وثائق مالية ومحاسبية', docs: 29 },
  { id: 'c3', name: 'Contracts', desc: 'العقود والاتفاقيات', docs: 21 },
  { id: 'c4', name: 'Reports', desc: 'تقارير دورية وتحليلية', docs: 14 },
];

export const ROLE_INFO = {
  admin: {
    label: 'Admin',
    name: 'أحمد المدير',
    initials: 'أح',
    dept: 'الإدارة العامة',
    email: 'admin@nuskha.org',
    badgeClass: 'badge-role-admin',
  },
  manager: {
    label: 'Manager',
    name: 'ليلى حسن',
    initials: 'لح',
    dept: 'المالية',
    email: 'layla.hassan@nuskha.org',
    badgeClass: 'badge-role-manager',
  },
  employee: {
    label: 'Employee',
    name: 'سارة الموظفة',
    initials: 'سم',
    dept: 'إدارة المشاريع',
    email: 'sara.emp@nuskha.org',
    badgeClass: 'badge-role-employee',
  },
};

export const CAT_NAMES = CATS.map((c) => c.name);
export const DEPT_NAMES = DEPTS.map((d) => d.name);
