
export const DOCS = [
  {
    id: 'leave-policy-2026',
    title: 'Employee leave policy 2026',
    cat: 'HR',
    dept: 'Human Resources',
    by: 'Ahmed Manager',
    date: '2026-06-28',
    desc: 'This document defines annual, sick, and emergency leave rules for employees, including request and approval procedures.',
    docDate: '2026-01-14',
    uploadedAt: '2026-01-15 · 10:32',
    updatedAt: '2026-02-02',
    files: [
      { id: 'f1', name: 'Leave request form.pdf', size: '240 KB', uploadedBy: 'Ahmed Manager' },
      { id: 'f2', name: 'Annual balance summary.xlsx', size: '88 KB', uploadedBy: 'Ahmed Manager' },
      { id: 'f3', name: 'Revisions addendum - Jan.docx', size: '54 KB', uploadedBy: 'Sarah Employee' },
    ],
  },
  {
    id: 'finance-report-q2',
    title: 'Quarterly financial performance report',
    cat: 'Finance',
    dept: 'Finance',
    by: 'Layla Hassan',
    date: '2026-06-25',
    desc: 'A detailed financial performance report for the second quarter of 2026.',
    docDate: '2026-06-20',
    uploadedAt: '2026-06-25 · 09:10',
    updatedAt: '2026-06-25',
    files: [{ id: 'f1', name: 'Q2 financial report.pdf', size: '512 KB', uploadedBy: 'Layla Hassan' }],
  },
  {
    id: 'office-supply-contract',
    title: 'Office supplies procurement contract',
    cat: 'Contracts',
    dept: 'Legal',
    by: 'Omar Yusuf',
    date: '2026-06-20',
    desc: 'Procurement contract for office equipment and furniture for the main headquarters.',
    docDate: '2026-06-15',
    uploadedAt: '2026-06-20 · 14:20',
    updatedAt: '2026-06-20',
    files: [{ id: 'f1', name: 'Signed contract.pdf', size: '310 KB', uploadedBy: 'Omar Yusuf' }],
  },
  {
    id: 'archiving-project-report',
    title: 'Document archiving project status report',
    cat: 'Reports',
    dept: 'Project Management',
    by: 'Sara Employee',
    date: '2026-06-18',
    desc: 'A periodic status report documenting progress on the digital document archiving project.',
    docDate: '2026-06-16',
    uploadedAt: '2026-06-18 · 11:05',
    updatedAt: '2026-06-18',
    files: [{ id: 'f1', name: 'Project report.docx', size: '120 KB', uploadedBy: 'Sara Employee' }],
  },
  {
    id: 'internal-hiring-guide',
    title: 'Internal hiring guide',
    cat: 'HR',
    dept: 'Human Resources',
    by: 'Ahmed Manager',
    date: '2026-06-12',
    desc: 'A guide to internal recruitment procedures and employee promotion policies.',
    docDate: '2026-06-01',
    uploadedAt: '2026-06-12 · 08:40',
    updatedAt: '2026-06-12',
    files: [{ id: 'f1', name: 'Hiring guide.pdf', size: '180 KB', uploadedBy: 'Ahmed Manager' }],
  },
  {
    id: 'hq-lease-contract',
    title: 'Headquarters lease agreement',
    cat: 'Contracts',
    dept: 'Legal',
    by: 'Omar Yusuf',
    date: '2026-06-05',
    desc: 'Annual lease agreement for the corporate headquarters.',
    docDate: '2026-05-28',
    uploadedAt: '2026-06-05 · 16:00',
    updatedAt: '2026-06-05',
    files: [{ id: 'f1', name: 'Lease agreement.pdf', size: '410 KB', uploadedBy: 'Omar Yusuf' }],
  },
  {
    id: 'budget-2027',
    title: 'Estimated budget 2027',
    cat: 'Finance',
    dept: 'Finance',
    by: 'Layla Hassan',
    date: '2026-05-30',
    desc: 'The projected budget for the 2027 fiscal year across all departments.',
    docDate: '2026-05-25',
    uploadedAt: '2026-05-30 · 13:15',
    updatedAt: '2026-05-30',
    files: [{ id: 'f1', name: 'Budget 2027.xlsx', size: '96 KB', uploadedBy: 'Layla Hassan' }],
  },
  {
    id: 'employee-satisfaction-report',
    title: 'Employee satisfaction survey report',
    cat: 'Reports',
    dept: 'Human Resources',
    by: 'Sara Employee',
    date: '2026-05-22',
    desc: 'Annual employee satisfaction survey results and improvement recommendations.',
    docDate: '2026-05-18',
    uploadedAt: '2026-05-22 · 10:50',
    updatedAt: '2026-05-22',
    files: [{ id: 'f1', name: 'Survey results.pdf', size: '275 KB', uploadedBy: 'Sara Employee' }],
  },
];

export const USERS = [
  { id: 'u1', name: 'Ahmed Manager', email: 'admin@nuskha.org', dept: 'General Management', role: 'Admin', active: true },
  { id: 'u2', name: 'Layla Hassan', email: 'layla.hassan@nuskha.org', dept: 'Finance', role: 'Manager', active: true },
  { id: 'u3', name: 'Omar Yusuf', email: 'omar.yousef@nuskha.org', dept: 'Legal', role: 'Manager', active: true },
  { id: 'u4', name: 'Sara Employee', email: 'sara.emp@nuskha.org', dept: 'Project Management', role: 'Employee', active: true },
  { id: 'u5', name: 'Khaled Nasser', email: 'khaled.n@nuskha.org', dept: 'Human Resources', role: 'Employee', active: false },
];

export const DEPTS = [
  { id: 'd1', name: 'Human Resources', desc: 'Staff, recruitment, and leave management', users: 5, docs: 32 },
  { id: 'd2', name: 'Finance', desc: 'Budgeting and financial reporting', users: 3, docs: 27 },
  { id: 'd3', name: 'Legal', desc: 'Contracts and legal documents', users: 2, docs: 19 },
  { id: 'd4', name: 'Project Management', desc: 'Internal project tracking', users: 6, docs: 24 },
];

export const CATS = [
  { id: 'c1', name: 'HR', desc: 'Human resources documents', docs: 38 },
  { id: 'c2', name: 'Finance', desc: 'Financial and accounting documents', docs: 29 },
  { id: 'c3', name: 'Contracts', desc: 'Contracts and agreements', docs: 21 },
  { id: 'c4', name: 'Reports', desc: 'Periodic reports and analytics', docs: 14 },
];

export const ROLE_INFO = {
  admin: {
    label: 'Admin',
    name: 'Ahmed Manager',
    initials: 'AM',
    dept: 'General Management',
    email: 'admin@nuskha.org',
    badgeClass: 'badge-role-admin',
  },
  manager: {
    label: 'Manager',
    name: 'Layla Hassan',
    initials: 'LH',
    dept: 'Finance',
    email: 'layla.hassan@nuskha.org',
    badgeClass: 'badge-role-manager',
  },
  employee: {
    label: 'Employee',
    name: 'Sara Employee',
    initials: 'SE',
    dept: 'Project Management',
    email: 'sara.emp@nuskha.org',
    badgeClass: 'badge-role-employee',
  },
};

export const CAT_NAMES = CATS.map((c) => c.name);
export const DEPT_NAMES = DEPTS.map((d) => d.name);
