export enum ActivityAction {
  LOGIN = 'LOGIN',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED', 
  REGISTER = 'REGISTER', 

  DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD',
  DOCUMENT_DOWNLOAD = 'DOCUMENT_DOWNLOAD',
  DOCUMENT_UPDATE = 'DOCUMENT_UPDATE',
  DOCUMENT_DELETE = 'DOCUMENT_DELETE',
  DOCUMENT_RESTORE = 'DOCUMENT_RESTORE',
  DOCUMENT_MOVE = 'DOCUMENT_MOVE',
  
  ATTACHMENT_UPLOAD = 'ATTACHMENT_UPLOAD',
  ATTACHMENT_DELETE = 'ATTACHMENT_DELETE',
  ATTACHMENT_DOWNLOAD = 'ATTACHMENT_DOWNLOAD',

  FOLDER_CREATE = 'FOLDER_CREATE',
  FOLDER_DELETE = 'FOLDER_DELETE',

  DEPARTMENT_CREATE = 'DEPARTMENT_CREATE',
  DEPARTMENT_UPDATE = 'DEPARTMENT_UPDATE',
  DEPARTMENT_DELETE = 'DEPARTMENT_DELETE',
  
  CATEGORY_CREATE = 'CATEGORY_CREATE',
  CATEGORY_UPDATE = 'CATEGORY_UPDATE',
  CATEGORY_DELETE = 'CATEGORY_DELETE',

  USER_UPDATE = 'USER_UPDATE',
  USER_STATUS_TOGGLE = 'USER_STATUS_TOGGLE',

  SETTINGS_UPDATE = 'SETTINGS_UPDATE',
}